### PR TITLE
[CI] Make params.env check happy again

### PR DESCRIPTION
**Pull request by jstourac**
No need for a workaround for the habana image anymore :)

### CODE REVIEW

**Comment by jstourac** [comment]
Just realized that we have an upstream -> downstream branch regular updates. So maybe this is irrelevant and I should just check that the appropriate changes are done in a relevant branch in upstream, right? I'm moving this to draft until it's clear.

**Comment by jstourac** [comment]
I'm undrafting this, since the change for this in main is for some time already 248047b5b0a984811c6e332f2149cc1cb4a61edb and the latest main -> 2024a PR #307 doesn't seem to grab it...

**Comment by atheo89** [comment]
Hey Jan this will sync on `release-2024a` automatically through this https://github.com/red-hat-data-services/notebooks/pull/307 (If the changes are merged on `2024a` upstream branch)

**Comment by jiridanek** [comment]
@atheo89 The PR you linked says it needs rebase. How to fix this? https://github.com/red-hat-data-services/notebooks/pull/307#issuecomment-2209199695

**Comment by atheo89** [comment]
@jiridanek It can be through GitHub UI, (I did that once) or checkout this PR and fix conflicts and push back.

**Comment by jstourac** [comment]
As was discussed above, the changes from upstream weren't brought in by the sync PRs, probably due to the manual changes due to the conflicts resolving or that Habana isn't in upstream. Anyway, since I forgot about this PR of mine in the meantime, this got fixed in this one instead #351. As such, this one can be closed as obsolete now :upside_down_face: :sunglasses:

**Pull request closed without merging**
