### PR TITLE
Upgrade the runtime images with rhods runtime,ref:80b11e7

### PR DESCRIPTION
**Pull request by harshad16**
Upgrade the runtime images with rhods runtime,ref:80b11e7

This would change the runtime image from reference of opendatahub to RHODS(modh) quay. 
Related-to: https://github.com/opendatahub-io/notebooks/issues/183

Reference: https://quay.io/repository/modh/runtime-images?tab=tags
commit id: `80b11e7`

### CODE REVIEW

**Review by atheo89 — COMMENTED** [review]
/lgtm

**Review by atheo89 — CHANGES_REQUESTED** [review]
Hey, just noticed a detail regarding the recent update. 
The sha digest is updated but we need also to update the registry! it points to workbenches

**Comment by atheo89** [comment]
You may find an open PR on the live-builder repo with the upgrade: 
https://gitlab.cee.redhat.com/data-hub/rhods-live-builder/-/merge_requests/248

**Comment by harshad16** [comment]
> Hey, just noticed a detail regarding the recent update. The sha digest is updated but we need also to update the registry! it points to workbenches

Good catch, thanks for spotting it.
I have made the change.

**Comment by harshad16** [comment]
> You may find an open PR on the live-builder repo with the upgrade: https://gitlab.cee.redhat.com/data-hub/rhods-live-builder/-/merge_requests/248

Thanks for PR.
we can update runtime-images in live-builder separately from notebook images
as with notebook image update , it would causes mis-match on self-managed cluster.

as the old notebook-images would be pointing to old set of runtime-images
where as the live -builder will pull in new runtime-images.
causing image-pullback error.

**Comment by harshad16** [comment]
Thanks for the review :100: 
/approve

**Pull request merged**
