### PR TITLE
[fix] hadolint warnings to base and rstudio Dockerfiles

### PR DESCRIPTION
**Pull request by jstourac**
These changes shouldn't have any functional impact.

https://issues.redhat.com/browse/RHOAIENG-7884

This is a followup of #169.

Waiting for #180. Then I rebase to see that this fix the CI completely.

Note: these files aren't in upstream, thus this change is for downstream repository right now.

Test locally:

```
find . -name "Dockerfile" | xargs hadolint --config ./ci/hadolint-config.yaml
```

### CODE REVIEW

**Review by atheo89 — COMMENTED** [review]
/lgtm

**Comment by jstourac** [comment]
The check failed with:

```
./manifests/base/params.yaml
  Warning: 106:3[8](https://github.com/red-hat-data-services/notebooks/actions/runs/8344911659/job/22838506170?pr=179#step:3:9) [new-line-at-end-of-file] no new line character at the end of file

./manifests/base/jupyter-minimal-notebook-imagestream.yaml
  Warning: 6[9](https://github.com/red-hat-data-services/notebooks/actions/runs/8344911659/job/22838506170?pr=179#step:3:11):21 [new-line-at-end-of-file] no new line character at the end of file

./manifests/base/jupyter-minimal-gpu-notebook-imagestream.yaml
  Warning: 69:21 [new-line-at-end-of-file] no new line character at the end of file
```

These were updated in this commit - 2623b0a767bcc5b58671cd28529015434d3a7393. Please let me know if we want to ignore this warning or whether I shall keep the warning in CI and fix these three files.

**Comment by jstourac** [comment]
Any objections from this being merged? :)

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve 

thanks for all the work :100:

**Review by jiridanek — APPROVED** [review]

**Comment by jstourac** [comment]
@harshad16 I wonder whether this shouldn't be backported to 2024a and 2023b branch at least, since the hadolint check is failing for this there https://github.com/red-hat-data-services/notebooks/actions/runs/9518814895/job/26240580087.

2023b doesn't have such check, so we may skip it.

Let me know, I can raise a PR.

**Comment by harshad16** [comment]
@jstourac , yes please raise it, if it is not present in those branches.

**Comment by jstourac** [comment]
@harshad16 I will do it only for the 2024a branch - hadolint is nice to have, although the other CI for checking manifests aren't that important in those branches. So I don't think it is worth the effort to have it in 2023b too. Please, let me know in  case I missed something in my consideration and we truly want it there also!

**Pull request merged**
