### PR TITLE
Fix the path to the params.env file

### PR DESCRIPTION
**Pull request by atheo89**
Fix the path to the params.env file

### CODE REVIEW

**Review by jstourac — APPROVED** [review]
LGTM overall, would be nice if you could also fix the name of `param.env` -> `params.env` on these two lines too:

* https://github.com/red-hat-data-services/notebooks/pull/67/files#diff-9aecd99a5a3ba71211db5313c274622b9bd587bf84d9f6cb149a089cfeb65fe7R73
* https://github.com/red-hat-data-services/notebooks/pull/67/files#diff-9aecd99a5a3ba71211db5313c274622b9bd587bf84d9f6cb149a089cfeb65fe7R123

it's optional though

**Review by jstourac — APPROVED** [review]

**Comment by atheo89** [comment]
> could also fix the name of param.env -> params.env
 
 Thanks, for your review! I just fixed it!

**Pull request merged**
