### PR TITLE
Remove Habana imagestream from RHOAI

### PR DESCRIPTION
**Pull request by atheo89**
Related to: https://issues.redhat.com/browse/RHOAIENG-15000 

Remove Habana ImageStreams from the notebooks manifests. Apply the changes to `/downstream/main`

### CODE REVIEW

**Comment by jiridanek** [comment]
I'm comparing this with the previous PR from @dibryant we had, to see if anything may be remaining
* https://github.com/red-hat-data-services/notebooks/pull/384

**Comment by jiridanek** [comment]
There is a little bit of habana left in opendatahub-io

* https://github.com/search?q=repo%3Aopendatahub-io%2Fnotebooks%20Habana&type=code
* and in red-hat-data-services seems like there are parallel bits https://github.com/search?q=repo%3Ared-hat-data-services%2Fnotebooks%20habana&type=code

image

shouldn't this be purged too?

**Comment by atheo89** [comment]
Thanks for the review, I didn't dive into the docs for this, but yeah maybe need to clean up them too. I will open a separated PR to clean upstream docs

**Comment by jiridanek** [comment]
separate PR for doc cleanup works for me
/lgtm

**Comment by atheo89** [comment]
Here it is: https://github.com/opendatahub-io/notebooks/pull/793 
I kept only one reference on this readme file https://github.com/opendatahub-io/notebooks/blob/main/manifests/base/README.md

**Comment by andyatmiami** [comment]
Only references I see to `habana` are covered by the related docs PR linked above.

image


/lgtm

**Pull request merged**
