### PR TITLE
RHOAIENG-16520: update setuptools to 70.0.0 for CVE fixes

### PR DESCRIPTION
**Pull request by dibryant**
Fixes for https://issues.redhat.com/browse/RHOAIENG-16520

updating setuptools to 70.0.0 to fix a few CVEs (unable to update those pipfile.locks that are missing)

### CODE REVIEW

**Comment by atheo89** [comment]
Hi Diamond here we need to update only the directories that are not in upstream.
So, keep the changes only the `amd/*` and `base/rhel9/*` the rest should be removed.

**Comment by jiridanek** [comment]
/retitle RHOAIENG-16520: updated setuptools to 70.0.0 for CVE fixes

**Comment by jiridanek** [comment]
/retitle RHOAIENG-16520: update setuptools to 70.0.0 for CVE fixes

**Pull request merged**
