### PR TITLE
[fix] hadolint warnings to base and rstudio Dockerfiles

### PR DESCRIPTION
**Pull request by jstourac**
These changes shouldn't have any functional impact.

This fixes the CI checks and should be cherry-picked to `main`.

---

But just now, when raising this. I'm thinking whether we actually want it in the `rhoai-2.8` in the end... Please, let me know, guys.

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve 


thanks :+1:

**Comment by riprasad** [comment]
@harshad16 We are in Code freeze and lets respect the protocol. Please do not accepts any changes in the release branch that doesn't have a blocker JIRA associated with it.

Please reset the branch to point 37e8782f58bef81fbd6bc91c98407df92a5fb6ca

**Comment by harshad16** [comment]
@riprasad Thanks for pointing us in the right direction. 
we have reverted to commit https://github.com/red-hat-data-services/notebooks/commit/37e8782f58bef81fbd6bc91c98407df92a5fb6ca in https://github.com/red-hat-data-services/notebooks/commits/rhoai-2.8/

@jstourac , please open a separate PR for `main`.

**Comment by jstourac** [comment]
@harshad16 Checking the `main` and looks like it doesn't contain the changes from upstream yet. I'll wait till it's time to do this then. Thanks.

**Pull request merged**
