### PR TITLE
[2023b] RHOAIENG-8299, RHOAIENG-8255, RHOAIENG-8740: Fix spawn-fcgi-1.6.3-23.fc37.x86_64.rpm and CentOS Stream 8 download locations

### PR DESCRIPTION
**Pull request by jiridanek**
https://issues.redhat.com/browse/RHOAIENG-8299, https://issues.redhat.com/browse/RHOAIENG-8255, https://issues.redhat.com/browse/RHOAIENG-8740

This cherry-picks the 2023 branch changes:

* https://github.com/opendatahub-io/notebooks/pull/570
* https://github.com/opendatahub-io/notebooks/pull/571

### CODE REVIEW

**Review by jstourac — APPROVED** [review]

**Comment by atheo89** [comment]
This changes incorporated on the release-2023b branch though this workflow: https://github.com/red-hat-data-services/notebooks/actions/runs/9566061878 

Could you verify as well if everything is in place? this is the last commit on the release-2023b branch https://github.com/red-hat-data-services/notebooks/commit/8f62b840aab6c18745dc23f436ac5dcf80a3abd2

**Comment by atheo89** [comment]
The RHEL is getting incorporated by main -> release-x.y

**Comment by jiridanek** [comment]
So, I don't have to create this PR because https://github.com/red-hat-data-services/notebooks/actions/runs/9566061878 has already done this for me? Great!

Well, there is this,

```
Could not solve for environment specs
The following packages are incompatible
├─ onnx ==1.12.0 py38h8d49f1e_0 is installable and it requires
│  └─ protobuf >=3.12.2,<=3.20.1 , which can be installed;
└─ protobuf ==3.20.3 py38h8dc9893_1 is not installable because it conflicts with any installable versions previously reported. 
```

**Comment by jiridanek** [comment]
I've rebased the PR, so here's the one remaining change that needs to be done that did not get in through the https://github.com/red-hat-data-services/notebooks/actions/runs/9566061878  sync.

**Review by harshad16 — APPROVED** [review]
/lgtm
/approve

thanks for this work :100:

**Comment by jiridanek** [comment]
```
Could not solve for environment specs
The following packages are incompatible
├─ onnx ==1.12.0 py38h8d49f1e_0 is installable and it requires
│  └─ protobuf >=3.12.2,<=3.20.1 , which can be installed;
└─ protobuf ==3.20.3 py38h8dc9893_1 is not installable because it conflicts with any installable versions previously reported. 
```

I seem to remember we don't care about Anaconda image. Does that still apply?

@harshad16 I figure it does. Can you please dismiss the failing test? And what's to be done about anaconda? Should I open a Jira?

**Pull request merged**
