### PR TITLE
[fix] hadolint warnings to base and rstudio Dockerfiles

### PR DESCRIPTION
**Pull request by jstourac**
These changes shouldn't have any functional impact.

(cherry picked from commit a674246700e9f2265fe112b66db6eb658252ffa7)

This is backport of #179; tracked in https://issues.redhat.com/browse/RHOAIENG-7884

### CODE REVIEW

**Comment by jiridanek** [comment]
> /retest

Won't help,

> : Build image jupyter-datascience-anaconda-python-3.8 from the repository expand_more

on 2023b never succeeds

**Comment by jstourac** [comment]
>>: Build image jupyter-datascience-anaconda-python-3.8 from the repository expand_more

> on 2023b never succeeds

I must have overlooked the anaconda failure before then, now I see it.

**Comment by jstourac** [comment]
Just realized that we have an upstream -> downstream branch regular updates. So maybe this is irrelevant and I should just check that the appropriate changes are done in a relevant branch in upstream, right? I'm moving this to draft until it's clear.

**Comment by jstourac** [comment]
> Just realized that we have an upstream -> downstream branch regular updates. So maybe this is irrelevant and I should just check that the appropriate changes are done in a relevant branch in upstream, right? I'm moving this to draft until it's clear.

Hehe, the files that are changed in this PR aren't upstream, so we can't rely on upstream->downstream sync in these cases. Undrafted, ready for refiew/merge.

**Comment by jstourac** [comment]
@harshad16 do you mind to give your review/opinion so we can merge this eventually?

**Comment by harshad16** [comment]
> do you mind to give your review/opinion so we can merge this eventually?

Could you please share why this is being pointed to the 2023b release branch? (i might seem have forgotten :see_no_evil: )
Till i remember, we are providing only build configs with on imagestream pointing to [latest](https://github.com/red-hat-data-services/notebooks/blob/5923bd64807ae255fc4b24e3a31ca695d5f7caf6/manifests/base/cuda-rstudio-buildconfig.yaml#L28) tag, so i m unable to recollect why we are targeting 2023b branch.

**Comment by jiridanek** [comment]
The Jira (and comment https://issues.redhat.com/browse/RHOAIENG-7884?focusedId=24934565&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-24934565 in it) is about putting the CI check (and necessary fixes) into all relevant branches. I'd put this in.

**Comment by harshad16** [comment]
Thank you for the response, lgtm.
/lgtm
/approve

**Pull request merged**
