### PR TITLE
HotFix: Replace with correct branch ref instead of main

### PR DESCRIPTION
**Pull request by harshad16**
HotFix: Replace with correct branch ref instead of main

https://issues.redhat.com/browse/RHOAIENG-4524

### CODE REVIEW

**Comment by jstourac** [comment]
It was decided not to do another RC because of this. Instead a workaround will be described to customers.

**Comment by harshad16** [comment]
Closing this as per above details.

**Comment by jiridanek** [comment]
/retitle  RHOAIENG-8314: Replace BuildConfig definition for RStudio with correct branch ref instead of main

**Pull request closed without merging**
