### PR TITLE
[main] sync main from opendatahub-io:main

### PR DESCRIPTION
**Pull request by harshad16**
Fixes: https://github.com/red-hat-data-services/notebooks/pull/359

sync main from opendatahub-io:main
this covers all the commits from opendatahub-io:main

created with following commands:
```
git checkout main
git checkout -b rsync-main
git remote add upstream <opendatahub-io/notebooks>
git pull upstream main --no-rebase
```

### CODE REVIEW

**Comment by jstourac** [comment]
Seems like one extra commit is needed here (not sure why it differs from upstream, though - @jiridanek ?):

```
Error: Please run 'bash ci/generate_code.sh' (the command from the previous step), commit the changed files locally, and push again.
```

**Comment by jiridanek** [comment]
I guess just syncing everything does not apply cleanly, see
* https://github.com/red-hat-data-services/notebooks/pull/359

**Comment by jstourac** [comment]
/lgtm

Though, the GH states this still has some conflicts even though no new commit was added to the main branch in the past 2 days :thinking:

**Pull request merged**
