### PR TITLE
Create a workflow that syncs the downstream branch with the upstream one

### PR DESCRIPTION
**Pull request by atheo89**
This PR adds a GitHub workflow on the downstream repository that is going to sync weekly the downstream release branch [2023a](https://github.com/red-hat-data-services/notebooks/tree/2023a) with the upstream [2023a](https://github.com/opendatahub-io/notebooks/tree/2023a)

Jira issue: https://issues.redhat.com/browse/RHODS-7323

### CODE REVIEW

**Comment by dchourasia** [comment]
looks good to me

**Comment by VaishnaviHire** [comment]
@atheo89 Just to confirm, this workflow is in addition to the one that syncs the downstream when a PR is merged ?

**Comment by atheo89** [comment]
Hey @VaishnaviHire This is a workflow will sync the downstream release branch 2023a with the upstream 2023a.
The reason for doing this is that on the upstream we will have the GitHub [workflow](https://github.com/opendatahub-io/notebooks/blob/main/.github/workflows/piplock-renewal-2023a.yml) that refreshes the piplock files every week which will push back the changes into the release branch(upstream). So, with this workflow, we will align the two branches together.

**Comment by dchourasia** [comment]
@atheo89  couple of things when I compared with the original one:

1. you will need to checkout the branch first
2. you will need a secret token while checking out, which has a repo level access to both the source and destination repos

Look at the implementation here https://github.com/red-hat-data-services/odh-dashboard/blob/auto-updater/.github/workflows/auto_updater.yaml

**Pull request merged**
