### PR TITLE
2024b r-sync

### PR DESCRIPTION
**Pull request by atheo89**
syncs 24b branch

### CODE REVIEW

**Comment by jiridanek** [comment]
are you doing to also fix image references check?

**Comment by jiridanek** [comment]
> Error: field specified in var '{odh-habana-notebook-image-commit-n ConfigMap.v1.[noGrp] {data.odh-habana-notebook-image-commit-n}}' not found in corresponding resource

looks like a legit error; manifests must be updated too

**Comment by atheo89** [comment]
> edit: actually, maybe not; it's important that the manifests in branch rhoai-2.14 are correct; the manifests here don't really matter for the product; so complicated

Exactly, the manifest should have correct values only on `main` and `rhoai-x.y` branches. The release-YYYYx branches are only for the builds.

**Comment by harshad16** [comment]
>Exactly, the manifest should have correct values only on main and rhoai-x.y branches. The release-YYYYx branches are only for the builds.

correct, i believe as this a sync PR
all the changes looks great, lets introduce this


/lgtm
/approve

**Comment by jiridanek** [comment]
/override code-static-analysis
ok then

**Comment by harshad16** [comment]
Merging this to ready the branch for builds.

**Pull request merged**
